### ISSUE TITLE
Question: which line number should an 'outdent' return?

### ISSUE THREAD

**Issue by benedfit** [pugjs/pug-lexer#12]
@ForbesLindesay: While looking at the reporting columns for tokens I noticed an difference in the line reporting of 'outdent' tokens depending on where they occur and was wondering whether this was intentional?

Take the following jade as an example:

``` jade
foo
  bar
foz
  baz
```

Which yields the following tokens:

``` js
[ { type: 'tag', line: 1, val: 'foo', selfClosing: false },
  { type: 'indent', line: 2, val: 2 },
  { type: 'tag', line: 2, val: 'bar', selfClosing: false },
  { type: 'outdent', line: 3 },
  { type: 'tag', line: 3, val: 'foz', selfClosing: false },
  { type: 'indent', line: 4, val: 2 },
  { type: 'tag', line: 4, val: 'baz', selfClosing: false },
  { type: 'outdent', line: 4 },
  { type: 'eos', line: 4 } ]
```

The first outdent is reported as being on line 3, essentially **before** `foz`. However the final outdent is reported as being on line 4, essentially **after** `baz`, which is correct as there is no line 5.

So it this intentional, or should the first outdent be reported as being on line 2?

**Comment by benedfit** [comment]
Having thought about this further it makes sense for it to be how it currently is

**Comment by ForbesLindesay** [comment]
What's there currently is very probably inconsistent/buggy because those specific tokens are highly unlikely to be used to emit error messages (which is currently the only place that line numbers are used).

If you feel like making a decision as to how it should be, and auditing the test cases to check they are all correct, then documenting how it should be in the readme, that would be awesome.

**Comment by benedfit** [comment]
Ok cool, if I see the need for any changes as part of the column reporting work I'm doing, I'll bundle them together and document them in the readme

**Comment by TimothyGu** [comment]
@benedfit are you still working on this?

**Comment by benedfit** [comment]
@TimothyGu I decided not to change anything regarding the line numbers for outdents, but I am still working on returning column numbers, however I've been away for 2 weeks, so will be ramping back up on it over the next few days
