### ISSUE TITLE
Syntax error reported for valid Jade

### ISSUE THREAD

**Issue by benedfit** [pugjs/pug-lexer#15]
`.test #[span.test= totalCurrentPage] | #[span.test= total]` currently reported as syntax error for the buffered code variables. However, testing this out on http://jade-lang.com/ does not throw an error

**Comment by ForbesLindesay** [comment]
This should now be fixed by #11.  Try installing the latest from the repo (it's not yet published to npm).

**Comment by ForbesLindesay** [comment]
Actually, hold off on that, it looks like it needs an update to character-parser first.

**Comment by benedfit** [comment]
Tests are currently failing on master too

**Comment by TimothyGu** [comment]
This bug has been fixed, but I'm just waiting for @ForbesLindesay to publish character-parser.

In the mean time, I pushed 76a039f so that at least the tests pass.
