### ISSUE TITLE
Should new lines after pipeless text be reported?

### ISSUE THREAD

**Issue by benedfit** [pugjs/pug-lexer#23]
e.g.

```
.
  foo
    bar
      baz
  .

```

yields

``` json
{"type":"dot","line":1}
{"type":"start-pipeless-text","line":1}
{"type":"text","line":2,"val":"foo"}
{"type":"newline","line":3}
{"type":"text","line":3,"val":"  bar"}
{"type":"newline","line":4}
{"type":"text","line":4,"val":"    baz"}
{"type":"newline","line":5}
{"type":"text","line":5,"val":"."}
{"type":"end-pipeless-text","line":5}
{"type":"eos","line":5}
```

I would expect the `eos` token to be preceded by a `newline` token, and the `eos` token to be reported as being on line 6, as per

```
p test

```

yields

``` json
{"type":"tag","line":1,"col":1,"val":"p","selfClosing":false}
{"type":"text","line":1,"col":3,"val":"test"}
{"type":"newline","line":2,"col":1}
{"type":"eos","line":2,"col":1}
```

**Comment by ForbesLindesay** [comment]
We currently don't report that token because when we get to a newline in pipeless text we actually insert a literal newline in the output, but we don't insert a newline at the start or end of the pipless text.

**Comment by benedfit** [comment]
Do you think we should for consistency?

On a more selfish note it means I need to rely on parsing the original source rather than querying the ATS for the Linter rule that requires line breaks at the end of files

**Comment by TimothyGu** [comment]
> Do you think we should for consistency?

I'd prefer compatibility over consistency in this case.

> On a more selfish note it means I need to rely on parsing the original source rather than querying the ATS for the Linter rule that requires line breaks at the end of files

A simple regex (or even `str[str.length - 1] === '\n'` check) can detect that pretty easily :)

**Comment by benedfit** [comment]
Cool. Thanks for the reply. I'll run with it as it is
