### ISSUE TITLE
Newlines in `call` tokens do not increment line number

### ISSUE THREAD

**Issue by benedfit** [pugjs/pug-lexer#26]
Spotted https://github.com/jadejs/jade-lexer/blob/master/test/cases/mixins.expected.json#L32-L33 while working on reporting column numbers. The newline character in the call token on line 32, should then cause the token on line 33 to be reported as being on line 18 rather than 17. 

I can pop a fix in as part of my work if you like?

**Comment by benedfit** [comment]
Proposed fix; add `this.incrementLine(tok.args.split("\n").length - 1);` after https://github.com/jadejs/jade-lexer/blob/master/index.js#L635

**Comment by ForbesLindesay** [comment]
Can you do it as a separate pull request? Makes them easier to review.

**Comment by benedfit** [comment]
Sure will do, an excuse my proposed fix containing code that relates to my other work
