### ISSUE TITLE
Should `text-html` capture any lines that contain HTML?

### ISSUE THREAD

**Issue by benedfit** [pugjs/pug-lexer#5]
Currently `p This is <strong>html</strong> text` yields the following tokens:

``` js
[ { type: 'tag', line: 1, val: 'p', selfClosing: false }
, { type: 'text', line: 1, val: 'This is <strong>html</strong> text' }
, { type: 'eos', line: 1 }
]
```

But should the `text` token be `text-html`, or is `text-html` only reserved for lines of text that start with HTML tags?

**Comment by ForbesLindesay** [comment]
It's only intended to catch lines that start with html.

**Comment by benedfit** [comment]
Other than wanting it for my own nefarious linting needs, could you see any benefits/disadvantages of modifying the lexer so that `p This is <strong>html</strong> text` would yield (or similar) the following?:

```
[ { type: 'tag', line: 1, val: 'p', selfClosing: false }
, { type: 'text', line: 1, val: 'This is ' }
, { type: 'text-html', line: 1, val: '<strong>html</strong>' }
, { type: 'text', line: 1, val: ' text' },
, { type: 'eos', line: 1 }
]
```

I'd be happy to submit a PR if you see any worth in this

**Comment by ForbesLindesay** [comment]
There's no real use for that, but also not much advantage to doing it other than for linting.  It's also actually a really difficult problem, figuring out where the html begins and ends reliably.  For example, what about:

``` jade
p This is <strong>#[em html]</strong> text
```

I would suggest that for linting you're best of just looking at all the "text" tokens and deciding what to do from there.

**Comment by benedfit** [comment]
Sure, I'm happy to to stick with the text tokens, thanks for your input
