### ISSUE TITLE
The json files under test/cases are not really json

### ISSUE THREAD

**Issue by lazytyper** [pugjs/pug-lexer#54]
The files are not really `json`, just each lines are json.

```
{"type":"newline","line":3,"col":1}
{"type":"tag","line":3,"col":1,"val":"ul"}
{"type":"indent","line":4,"col":1,"val":2}
...
```

With a little trick you could turn them into json: use an `array`:

```
[
    {"type":"newline","line":3,"col":1},
    {"type":"tag","line":3,"col":1,"val":"ul"},
    {"type":"indent","line":4,"col":1,"val":2}
    ...
]
```

And json files can be read with the `require()` function. ;)

**Comment by TimothyGu** [comment]
We have discussed this somewhere else (can't remember), but it was decided that newline-delimited JSON was easier to read.
