### ISSUE TITLE
Riot compatibility

### ISSUE THREAD

**Issue by ViableClanMember** [pugjs/pug-lexer#83]
Greetings, I hope this is the right place for this issue.

In Riotjs, we do `<ul each={item in items}></ul>` but in Pug, this code is invalid: `ul(each={item in items}) {item}`, so we have to wrap the Riot as a string like so: `ul(each="{item in items}") {item}`.

But then we lose linting.

Would it be possible to have an option to allow spaces within the {}'s, or any other such solution so I can have Riot+Pug+linting?

Many thanks in advance

**Comment by ForbesLindesay** [comment]
No, pug attributes are JavaScript expressions, you cannot put arbitrary text there without quotes.
