### ISSUE TITLE
Report line and column numbers wherever possible

### ISSUE THREAD

**Issue by benedfit** [pugjs/pug-lexer#9]
I'm going to start work in a fork (https://github.com/benedfit/jade-lexer) to report line and column numbers for tokens, and any errors encountered during lexing. Will keep you posted on my progress

**Comment by ForbesLindesay** [comment]
Excellent, I've been thinking we should do this for a while.  Specifically, it has the potential to allow us to support source maps.

**Comment by benedfit** [comment]
The sheer volume of test cases to check makes this quite a task, I'm making headway, but it's slow going

**Comment by benedfit** [comment]
70+% of test cases are now working, so I hope to have this cracked next week. I've be merging in upstream as I go to keep up-to-date

**Comment by TimothyGu** [comment]
@benedfit cool thanks!

**Comment by ForbesLindesay** [comment]
This has been merged :+1:
